spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  application:
    name: moyamoya
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 1234
discord:
  webhook-url: ${DISCORD_WEBHOOK_URL}
neis:
  api-key: ${NEIS_API_KEY}
jwt:
  secret-key: ${JWT_SECRET_KEY}
  expired:
    access: 3_600_000 # 1h
    refresh: 7_884_000_000 # 2M
coolsms:
  api-key: ${COOL_SMS_API_KEY}
  api-secret: ${COOL_SMS_API_SECRET}
  sender-phone: ${COOL_SMS_SENDER_PHONE}
cloud:
  aws:
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}
    s3-bucket: ${S3_BUCKET}
    stack:
      auto: false
    region:
      static: ${S3_REGION}
dev:
  secret-key: ${DEV_SECRET_KEY}
springdoc:
  swagger-ui:
    groups-order: DESC # path, query, body, response 순으로 출력
    tags-sorter: alpha # 태그를 알파벳 순으로 정렬
    operations-sorter: method  # delete - get - patch - post - put 순으로 정렬, alpha를 사용하면 알파벳 순으로 정렬 가능